### ISSUE TITLE
Make an optimized Lucene variant

### ISSUE THREAD

**Issue by LifeIsStrange** [quickwit-inc/tantivy#1210]
Hi @fulmicoton :)
For the benchmark to be really fair, major optimizations such as concurrent queries should be used.
-> https://blog.mikemccandless.com/2019/10/concurrent-query-execution-in-apache.html?m=1

**Comment by shikhar** [comment]
tantivy does support that! https://github.com/quickwit-inc/tantivy/blob/02174d26af50af2cf8b9f7592c35e90aae14de70/src/core/index.rs#L217-L222

I think it is fair since the benchmark does not enable it for tantivy either, AFAIK?

BTW, I gave a [talk about segment-level parallelism at Lucene Revolution 2015](https://lucidworks.com/post/search-time-parallelism-an-experiment-with-apache-lucene/). It was a lot of refactoring to be able to experiment. I'm not caught up on the current status with Lucene, but I don't think it is widely used.

So happy to see tantivy push Rust's fearless concurrency for parallelizing search execution across segments, and make it easy as flipping a switch.

Both Lucene and tantivy will be prone to the segment structure (cost will be dominated by largest segment), so while I'm curious what the numbers look like, it'll make the results noisy. What's most interesting to me in this benchmark is single-threaded performance, even if we are down to a fully merged index (1 segment). Does the benchmark already do a full merge?

**Comment by shikhar** [comment]
Oh this is really cool, the post you linked to mentions `The algorithm for grouping small segments into slices (thread work units) has improved.` https://issues.apache.org/jira/browse/LUCENE-8757

~That makes Lucene less prone to segment structure being uneven, than Tantivy.~

ED: no, it is not able to slice beyond segment granularity. Looks like it improved on previous approach of thread per segment, to better allocate multiple segments per thread. Tantivy uses a bounded thread pool.

**Comment by fmassot** [comment]
In the current benchmark, all queries are executed sequentially, you can see it here:
https://github.com/quickwit-inc/search-benchmark-game/blob/master/src/client.py

For the full merge question, the answer is yes, there is a full merge to have only one segment at the ned, you can see here for lucene: 
https://github.com/quickwit-inc/search-benchmark-game/blob/master/engines/lucene-8.10.1/src/main/java/BuildIndex.java#L49

**Comment by shikhar** [comment]
and i see we do the same for tantivy https://github.com/quickwit-inc/search-benchmark-game/blob/3d1d431ce8b642d34f89d7bef27194d0c5f06ab7/engines/tantivy-0.16/src/bin/build_index.rs#L49-L50

**Comment by shikhar** [comment]
With 1 segment currently for both Lucene & Tantivy, turning on multi-threaded search won't really make a difference :-) But maybe this issue can be about enhancing the benchmark to add multi-threaded variants, with whatever segment structure they end up at without a full merge.

**Comment by fmassot** [comment]
Regarding the opportunity to enhance the benchmark with concurrent queries, I suggest opening an issue on the [search benchmark repository](https://github.com/quickwit-inc/search-benchmark-game) to discuss that, there is definitely some room for improvement.

**Comment by fulmicoton** [comment]
This benchmark is most useful for tantivy, Lucene, PISA developers to identify query specific headroom.
Adding mutlithreading would only make the results noisy and the comparison impossible.

**Comment by PSeitz** [comment]
Multi-threaded tests (or load tests) can be good to see the scalability or bottle necks on the engine e.g. mem, cpu, io. I don't think comparison is impossible, but can be really really hard, since benchmarks are often already single-threaded super flaky.
