### ISSUE TITLE
Is it possible to delete documents from tantivy's index?

### ISSUE THREAD

**Issue by laptou** [quickwit-inc/tantivy#1245]
I want to run Tantivy on mobile devices, with the goal of indexing items that the user has clicked on recently so that they can be recalled quickly. I would like to limit the size of Tantivy's index, preferably having newer documents push out older documents as needed so that the index tops out at a certain maximum size. Is there a way to accomplish this?

**Comment by fmassot** [comment]
Hi @laptou! Yes this is possible, there is an example here: https://github.com/quickwit-inc/tantivy/blob/main/examples/deleting_updating_documents.rs
You will notice that you need to call `delete_term` which deletes all documents with the given term. 
Here the term should be the ID of your document if you want to delete precisely a document of a given ID.

But for your use case, I would do things differently: I would try to have one segment per a given period (one day for example) and when this segment is too old, delete it.
The problem is that this will require some work and I guess you are using some merge policy so you will need to adapt it too.
You may be interested in [Quickwit](https://github.com/quickwit-inc/quickwit/) because it has a time sharding feature that enables to easily remove old indexed documents.

**Comment by laptou** [comment]
Awesome, thanks for the guidance :)
