### ISSUE TITLE
Altering compression and/or IndexSortByField

### ISSUE THREAD

**Issue by ppodolsky** [quickwit-inc/tantivy#1371]
As far as I found changing of `DocStore` compression format for existing index is possible by design. But it is impossible in practice because of mutability rules and cloning inside Tantivy. 
In particular, the way to change compression codec might be `index_writer.index().settings_mut().compression = <desired compression>` and then calling `commit` within `index_writer`.
But this way fails because `index_writer.index()` returns immutable reference on `Index`. The second issue is that `Index` implements `Clone` and mutating `index_writer.index` will lead to diverging of content of multiple `Index` objects inside Tantivy.

What do you think? Is this an issue? If not, what is the reason of making `settings_mut()` public?

**Comment by fulmicoton** [comment]
It seems like @PSeitz made changing the compression format possible, and ensured that merging was working correctly.
There is even a unit test for that.

> But this way fails because index_writer.index() returns immutable reference on Index. The second issue is that Index implements Clone and mutating index_writer.index will lead to diverging of content of multiple Index objects inside Tantivy.

That's only a problem because you are getting your index from the index writer. When you open your index you have access to an `Index` object that can be mut if you want.
