### ISSUE TITLE
CLI merge fails on fresh index

### ISSUE THREAD

**Issue by kstaken** [quickwit-inc/tantivy#1375]
Maybe this is just a usage error since I'm new to tantivy but I created a fresh index, added some data and then attempted to merge all the segments and received an error.

```
$ tantivy --help | head -1
Tantivy 0.15.0
$ tantivy new --index new
$ cat input.json | tantivy index --index ./new/
$ tantivy merge --index ./new
Merge failed : SystemError("Merge failed:oneshot canceled")
```

The ingest created 4 segments.

```
{
  "index_settings": {
    "docstore_compression": "lz4"
  },
  "segments": [
    {
      "segment_id": "52078824-8755-477f-95c7-4713bb380f36",
      "max_doc": 35682,
      "deletes": null
    },
    {
      "segment_id": "4374a9ec-8123-4678-a687-e97aa2d6b0bd",
      "max_doc": 33667,
      "deletes": null
    },
    {
      "segment_id": "9405027a-8458-447b-90d7-755fa9484789",
      "max_doc": 30651,
      "deletes": null
    },
    {
      "segment_id": "ebce0f85-f706-4914-b474-22033fdd15cc",
      "max_doc": 1,
      "deletes": null
    }
  ],
  "schema": [
    {
      "name": "station_id",
      "type": "text",
      "options": {
        "indexing": {
          "record": "basic",
          "tokenizer": "raw"
        },
        "stored": true
      }
    },
    {
      "name": "name",
      "type": "text",
      "options": {
        "indexing": {
          "record": "freq",
          "tokenizer": "en_stem"
        },
        "stored": true
      }
    },
    {
      "name": "temperature_c",
      "type": "f64",
      "options": {
        "indexed": true,
        "fast": "single",
        "stored": true
      }
    }
  ],
  "opstamp": 100005
}
```

**Comment by kstaken** [comment]
I found that single doc segment to look suspect so I reduced the input size by 1 record and the merge succeeded. So with 100,000 input docs merge failed, succeeded with 99,999.

**Comment by fulmicoton** [comment]
I am not able to reproduce.
Tantivy-cli is lagging in tantivy version, but if you installed it recently via `cargo install` it should have picked tantivy 0.15.3.
Looking at the changelog it does not seem like a bug that was spotted and fixed later.

1- if you still have a directory with the faulty index, can you make a backup of it
2-  is it somethign that you can reproduce easily (meaning by redindexing from scratch.
You can create an extra 1 doc index by incrementally adding one segment 

```bash
head -n 1 wiki100k.json|  tantivy index --index .
```

3- is it possible for you to share the faulty index (provided you have one)? 
if 3 is impossible, because it is sensible data, I can try and add proper logging to tantivy-cli 0.15 and work off the logs.

**Comment by kstaken** [comment]
Sorry, missed the questions here.

I was able to repeatedly reproduce this with tantivy 0.15.0 but I've since tried tantivy built from source and have not been able to reproduce it. Newer versions don't create the single doc segment and I haven't seen any further merge failures.

As you suggested I also tried just adding a single document to an existing index and then merging and that does not appear to be a problem either.

It seems whatever the issue was it has likely been fixed somewhere along the way. I'm going close this, if I find a scenario where it occurs again I'll reopen and add more detail.
