### ISSUE TITLE
`NOT` and `-` operators not always consistent

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/tantivy#1433]
Here is a test that is failing on the second assertion

```rust
#[test]
fn test_parse_test_not() {
    test_parse_query_to_ast_helper("tata -toto", "(*\"tata\" -\"toto\")");
    test_parse_query_to_ast_helper("tata NOT toto", "(*\"tata\" -\"toto\")");
}
```

with output

```bash
thread 'query_grammar::test::test_parse_test_query_other' panicked at 'assertion failed: `(left == right)`
  left: `"(*\"tata\" *(-\"toto\"))"`,
 right: `"(*\"tata\" -\"toto\")"`', query-grammar/src/query_grammar.rs:445:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I would have expected the same behavior from the operator "-" and "NOT".

**Comment by bazhenov** [comment]
This happens basically because two provided queries parse results are different:

1. _tata -toto_ parsed down to 2 simple clauses
    ```
    Clause([
      (None,          Leaf("tata")),
      (Some(MustNot), Leaf("toto"))
    ])
    ```
2. while _tata NOT toto_ producing nested second clause:
    ```
    Clause([
      (None,          Leaf("tata")),
      (None,          Clause([
        (Some(MustNot), Leaf("toto"))
      ]))
    ])
    ```

I think this issue can be fixed by optimizing `UserInputAst` after it has been parsed from string. The optimization rule is quite simple. Each element in `UserInputAst::Clause` vector can be replaced by it's inner single clause if `Occur` is missing.

`(None, UserInputAst::Clause(v))` → `(v[0].0, v[0].1)` if and only if `v.len() == 1`.

I can provide PR.

**Comment by bazhenov** [comment]
#1609

**Comment by trinity-1686a** [comment]
this has been fixed, and there is a [test to detect regression](https://github.com/quickwit-oss/tantivy/blob/1a9fc10be981b681f891359757926684ada2405c/query-grammar/src/query_grammar.rs#L1593-L1596), closing
