### ISSUE TITLE
Add a configurable RegexTokenizer

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/tantivy#1670]
The regex pattern woudl be a parameter of the tokenizer.
The tokenizer would "search" the regex and emit one token per match.

**Comment by Gearme** [comment]
PR #1758 - let me know what you think.

**Comment by fulmicoton** [comment]
@gearme @mkleen your contributions seem to have strangely collisionned. This is an interesting occurence actually.
Can you have a look at your respective PRs,  and discuss them?

**Comment by Gearme** [comment]
Agreed - still can't believe we were only like 2min apart! But it's still just a coincidence, there's no motivation behind it.
I chose this issue for a contribution simply as an exercise in FOSS contribution though, while @mkleen mentioned a use case he has - maybe he could look at whether the use case is covered by my implementation?
Otherwise, from what I can see it comes down to whether support for capture groups in Tokenizers is valuable to tantivy - in the interest of parity with Lucene, that seems a reasonable assumption to me.

**Comment by mkleen** [comment]
@fulmicoton yes sure, this makes sense. We will figure something out. Thanks for your feedback! RegexTokenizer was the only issue labeled with "Help wanted", so this might be the reason we both picked it up. So maybe it make sense to add this label more often if possible.

**Comment by Gearme** [comment]
Exactly, that's why I picked it up as well - that and the fact that it seemed to require only a very localized implementation.

**Comment by mkleen** [comment]
@Gearme I am ok with you taking over this task, because your implementation is feature-wise superior to my one. So if it's ok with @fulmicoton I would just close my pr and @Gearme can go ahead.
