### ISSUE TITLE
Add cardinality aggregation.

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/tantivy#2248]
It's already tracked in [Quickwit](https://github.com/quickwit-oss/quickwit/issues/3779) but not in tantivy. 

This is the same aggregation as the one defined in [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html)

**Comment by saroh** [comment]
I gave a quick look, unfortunately no time to implem but here are a few pointers for someone else, or future me :D 

<details><summary>Spoilers ??????</summary>
<p>
The code should be pretty similar to the percentiles aggregation (see implem PR #1984)

`PercentilesCollector` -> `CardinalityCollector` which would hold a hyperloglog implementing add, merge and count.

hashing -> values need to be hashed in order to map them to a uniform distribution. It's possible the hll implem hashes => need to make sure the hash is computent just once

missing values -> it may be faster to simply check if we've seen a missing value and add +1 to the final count rather than blindly adding the same value's hash to the hll each time we encounter one.

</p>
</details>
