### ISSUE TITLE
tantivy vs Lucene benchmark confusion

### ISSUE THREAD

**Issue by rodion-m** [quickwit-inc/tantivy#2365]
Hi tantivy team!

[Here is](https://github.com/quickwit-oss/tantivy?tab=readme-ov-file#on-average-how-much-faster-is-tantivy-compared-to-lucene) written that:

> According to our [search latency benchmark](https://tantivy-search.github.io/bench/), Tantivy is approximately 2x faster than Lucene.

But in the provided benchmark tantivy has greater latency than Lucene. What do I read wrong?
![image](https://github.com/quickwit-oss/tantivy/assets/36400912/ce7b1402-4ad7-411d-b45c-e0378063acfb)

**Comment by PSeitz** [comment]
Check the the top `TOP_100_COUNT` collection type. You usually want a count with your results

**Comment by rodion-m** [comment]
@PSeitz  Oh, thank you for the answer! I didn't get what means "COUNT" at first. It's a match similarity rate, right?

**Comment by PSeitz** [comment]
COUNT is just the number of results. btw. tantivy `0.22` got some performance upgrades

**Comment by rodion-m** [comment]
@PSeitz Then I still didn't catch this. Sorry, I haven't work too much with FTS. Why do we need the count of TOP 100? Wouldn't we always get 100 in such a case (assuming there are more than 100 documents in the table)?

**Comment by PSeitz** [comment]
It's the top 100 results + total count

**Comment by varenc** [comment]
I had the same confusion and then found this issue. If `TOP_100_COUNT` is a more representative collection type than perhaps it should be the default on that page? I was quite confused after reading that "_Tantivy is approximately 2x faster than Lucene_" but then seeing that the linked benchmarked doesn't show that.  Took me awhile to convince myself that I wasn't just mis-reading it.

**Comment by fulmicoton** [comment]
I think we can update this sentence. The truth is Lucene recently added a lot of optimization, we updated the results and did not update the text. and the story is not as clear as "tantivy is 2x faster than Lucene".

COUNT: just count documents. This is not what people think of as search
TOP K:  identify the top K most relevant documents
TOP K + COUNT: Do both. This can be a decent proxy for anythign a little bit complicated, since the first two have specific optimization that do not generalize well.
