### ISSUE TITLE
Exists query does not work

### ISSUE THREAD

**Issue by Zhincore** [quickwit-inc/tantivy#2508]
**Describe the bug**
- I am trying to run an exists query through `QueryParser`, for example `name:*`.
- I get this error: `Unsupported query: Range query need to target a specific field.`, I assume #2218 is related.
- I expected to get a query that matches all items with a name

**Which version of tantivy are you using?**
0.22.0

**To Reproduce**
1. Have a Tantivy setup, I didn't find any correlation with field types or anything.
2. Have QueryParser, e.g. `let query_parser = QueryParser::for_index(&index, vec![ ...your default fields... ])`
3. **Try** to parse an exists query `query_parser.parse_query("name:*")`
4. You get the above error :(

**Comment by LebranceBW** [comment]
It's odd that [ExistsQuery](https://github.com/quickwit-oss/tantivy/blob/2f5a269c70855afb983fa3fb5d299fa0001f713f/src/query/exist_query.rs#L16) has been implemented, but this particular query pattern does not utilize it. 

If there's no specific reason behind it, I'd be happy to hook them up.

**Comment by fulmicoton** [comment]
`ExistsQuery` work. They are not integrated with the query parser. This is not a bug as long as documentation says otherwise.

Closing this issue. 

@LebranceBW 
It has been implemented for Quickwit, which uses its own query parser.
Generally speaking I strongly recommend people building something serious to implement their own query parser.
Feel free to open a feature ticket if you want to contribute the addition of this syntax in tantivy's query parser.

**Comment by LebranceBW** [comment]
> `ExistsQuery` work. They are not integrated with the query parser. This is not a bug as long as documentation says otherwise.
> 
> Closing this issue.
> 
> @LebranceBW It has been implemented for Quickwit, which uses its own query parser. Generally speaking I strongly recommend people building something serious to implement their own query parser. Feel free to open a feature ticket if you want to contribute the addition of this syntax in tantivy's query parser.

I've submitted issue #2514 and PR #2513 for the newly supported syntax. Could you please take a moment to review them? @fulmicoton
